"""add vendor and vendor_links

Revision ID: 5ad67785ca96
Revises: 9ecf7526c788
Create Date: 2017-04-21 16:33:11.925830

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5ad67785ca96'
down_revision = '9ecf7526c788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vendor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('logo_url', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor'))
    )
    op.create_table(
        'vendor_link',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('currency', sqlalchemy_utils.types.currency.CurrencyType(
            length=3), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f(
            'fk_vendor_link_post_id_post'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f(
            'fk_vendor_link_vendor_id_vendor'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_link'))
    )
    op.alter_column(
        'post', 'fb_page_id',
        existing_type=sa.TEXT(),
        nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'post', 'fb_page_id',
        existing_type=sa.TEXT(),
        nullable=False)
    op.drop_table('vendor_link')
    op.drop_table('vendor')
    # ### end Alembic commands ###
