"""add guest user table

Revision ID: bfa884e2847e
Revises: 3b12a5bb5842
Create Date: 2017-08-04 15:42:22.271126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa884e2847e'
down_revision = '3b12a5bb5842'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('guest_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('account', sa.String(length=64), nullable=False),
                    sa.Column('password',
                              sa.String(length=128), nullable=False),
                    sa.Column('country', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_users')))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_users')
    # ### end Alembic commands ###
